server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /bo-portal

security:
  internal-secret: ${INTERNAL_SECRET_KEY:defaultSecretValue}
  internal-path-prefix: /bo-portal/internal/

spring:
  application:
    name: bo-portal
  profiles:
    active: prod
  config:
    import:
      - 'classpath:client.yml'

feign:
  client:
    config:
      auth-service:
        url: ${AUTH_SERVICE_URL:http://localhost:8888}
      hrm-service:
        url: ${HRM_SERVICE_URL:http://localhost:8080}
      lms-service:
        url: ${LMS_SERVICE_URL:http://localhost:6666}
  jackson:
  #    deserialization:
  #      read-date-timestamps-as-nanoseconds: false
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:}
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    secret: ${APP_JWT_SECRET:}
    public: ${APP_JWT_PUBLIC:}
    token:
      expires-in: ${APP_JWT_TOKEN_EXPIRES_IN:#{60 * 60 * 1000}} # 60 minutes in milliseconds
    refresh-token:
      expires-in: ${APP_JWT_REFRESH_TOKEN_EXPIRES_IN:#{24 * 60 * 60 * 1000}} # 24 hours in milliseconds
    remember-me:
      expires-in: ${APP_JWT_REMEMBER_ME_EXPIRES_IN:#{24 * 60 * 60 * 1000 * 7}} # 7 days in milliseconds

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

configuration:
  timezone: ${TIMEZONE_CONFIG:Asia/Ho_Chi_Minh}

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - prometheus
          - health
          - metrics
      path-mapping:
        health: /actuator/health
        prometheus: /actuator/prometheus
        metrics: /actuator/metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
      show-components: always
  metrics:
    distribution:
      percentiles-histogram:
        "http.server.requests": true
        "http.client.requests": true
      percentiles:
        "http.server.requests": 0.5, 0.90, 0.95, 0.99
        "http.client.requests": 0.5, 0.90, 0.95, 0.99

idempotence:
  spring:
    package-to-scan: com.fis.boportalservice

logging:
  sensitive-fields: ${SENSITIVE_DATA:access_token,cvv,url}

threadPool:
  asyncTask:
    maxPoolSize: 10
    corePoolSize: 5
    queueCapacity: 10000

application:
  cache-ttl-default-days: 3

services:
  gateway:
    url: ${GATEWAY_URL:http://localhost:8765}
